#include <SFML/Graphics.hpp>
#include <cmath>

#define WINDOW_TITLE "Best Game"
#define FPS 60

#define WINDOW_WIDTH 900
#define WINDOW_HEIGHT 900

#define SPRITE_SIZE 50

#define GRASS_START 10
#define GRASSEATERS_START 12
#define HUNTERS_START 4

#define LIFE_TIME_HUNTERS 800
#define LIFE_TIME_GRASSEATERS 1600
#define HUNGER_DEATH 550
#define HUNGER 300
#define SEX 250
#define GRASSEATERS_SEX 100

#define MIN_RAIN_TIME 100
#define RAIN_SPEED 10
#define RAIN_CONST 300
#define HUNTERS_MOVEMENT_SPEED 220
#define MOVEMENT_SPEED 200