#include <SFML/Graphics.hpp>
#include <cmath>

#define WINDOW_TITLE "Best Game"
#define FPS 60

#define WINDOW_WIDTH 900
#define WINDOW_HEIGHT 900

#define SPRITE_SIZE 50

#define GRASS_START 10
#define GRASSEATERS_START 12
#define HUNTERS_START 4

#define HUNTERS_LIFE_TIME 800
#define GRASSEATERS_LIFE_TIME 1600
#define GRASSEATERS_HUNGER_DEATH 550
#define HUNTERS_HUNGER_DEATH 500
#define HUNTERS_HUNGER 300
#define GRASSEATERS_HUNGER 300
#define HUNTERS_SEX 250
#define GRASSEATERS_SEX 200

#define HUNTERS_MOVEMENT_SPEED 220
#define GRASSEATERS_MOVEMENT_SPEED 200

#define MIN_RAIN_TIME 100
#define RAIN_SPEED 10
#define RAIN_CONST 300